openapi: 3.0.0
info:
  title: openapi
  version: 1.0.0
paths:
  /history:
    get:
      summary: get list of annotations
      operationId: >-
        users_yisehak_documents_bruno_mozi_annotation_get_list_of_annotations_yml
      description: ''
      tags:
        - annotation
      responses:
        '200':
          description: ''
      servers:
        - url: https://dev.rejuve.bio:5050
  /auth/login:
    post:
      summary: login
      operationId: users_yisehak_documents_bruno_mozi_auth_login_yml
      description: ''
      tags:
        - auth
      responses:
        '200':
          description: ''
      requestBody:
        $ref: '#/components/requestBodies/login'
      servers:
        - url: https://dev.rejuve.bio:5052
servers: []
components:
  schemas:
    login:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: '{{email}}'
        password: '{{password}}'
  requestBodies:
    login:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/login'
      description: ''
      required: true
  securitySchemes: {}
